name: Docker Image CI

on:
  push:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/imgpharmstock:latest
      -  
        name: connect ssh
        # uses: appleboy/ssh-action@master
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/imgnurul
            docker run --name ${{ secrets.CNAME }} -p 8000:8000 -d -e SERVER=8000 -e DBPORT=3306 -e DBHOST=${{secrets.DBHOST}} -e DBUSER=${{secrets.DBUSER}} -e DBPASS=${{secrets.DBPASS}} -e DBNAME=${{secrets.DBNAME}} -e SECRET=${{secrets.SECRET}} -e OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}} -e CLOUD_NAME=${{secrets.CLOUD_NAME}} -e CLOUD_APIKEY=${{secrets.CLOUD_APIKEY}} -e CLOUD_SECRET=${{secrets.CLOUD_SECRET}} ${{ secrets.DOCKERHUB_USERNAME }}/imgpharmstock
